### ISSUE TITLE
More Lint cops should be enabled by default

### ISSUE THREAD

**Issue by jaynetics** [rails/rubocop-rails-omakase#12]
Disclaimer: I've read the disclaimer and I'm very happy about the unintrusive mindset :)

That being said, I think there are some cops that would benefit future users of this styleguide without making anything more rigid.

AFAIU, this will be the default rubocop configuration for newcomers to rails, and thus for inexperienced and small crews.

I think this audience would benefit if some Lint cops were enabled by default that are not so much a question of style, but rather trigger exclusively for coding mistakes:

- Lint/IneffectiveAccessModifier
- Lint/DuplicateCaseCondition
- Lint/DuplicateElsifCondition
- Lint/DuplicateHashKey
- Lint/DuplicateMatchPattern
- Lint/DuplicateMethods
- Lint/DuplicateRescueException
- Lint/RandOne

IMO these only ever prevent mistakes and confusion, and I can't think of a reason to have them turned off. There might be more of this type. Of course people can enable them on their own, but they will have to find the right ones.

Then there are some Lint cops that are *almost* certain to indicate mistakes:

- Lint/CircularArgumentReference
- Lint/LiteralAsCondition
- Lint/RegexpAsCondition
- Lint/Void
- ... and maybe more

I can see how these could be a matter of taste, if quick and dirty hacks such as the following should stay permitted:

```diff
-if foo? && bar?
+if true # foo? && bar?
   do_something
 end
```

However, I don't think the same benefit of the doubt can be extended to the first group.

**Comment by jeremy** [comment]
A "guardrails" configuration would be interesting but is indeed out of scope here where we're focused solely on Rails Omakase style. Could do a wrapper that includes rubocop-rails-omakase and also provides a solid, unobtrusive set of linters in a similar spirit.
