### ISSUE TITLE
Add the MIT License file

### ISSUE THREAD

**Issue by rgisiger** [rails/rubocop-rails-omakase#20]
Is it possible to add the MIT License file ?

**Comment by dhh** [comment]
The license is specified and linked in the README. Don't see the value of adding it to all projects as a distinct file.

**Comment by rgisiger** [comment]
Yes I have seen it but the link is incorrect since the template is not filled correctly.

The copyright holder statement is missing and including it in its own LICENSE file helps the ones who use it since the project is delivered as a Gem.

This [comment on another project](https://github.com/tomerfiliba-org/reedsolomon/issues/30#issue-821197711) states the same.
